version: '3'

name: limb

services:
  limb:
    image: node:20-alpine
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: |
      /opt/app/server-main.js
    environment:
      NODE_ENV: production
      DEBUG: limb:*
    volumes:
      - ./build:/opt/app:ro

    # logging: &log_fluentd
    #   driver: fluentd
    #   options:
    #     fluentd-address: "127.0.0.1:24224"
    #     fluentd-async-connect: "true"
    #     tag: container-{{.Name}}-{{.ID}}
